### PR TITLE
fix/knit_config

### PR DESCRIPTION
**Pull request by quasiben**
Needed to add various hdfs and yarn config parameters available to dask-yarn.

Currently, the default is still `autodetect=True`.  How do others feel about his ?

### CODE REVIEW

**Comment by mrocklin** [comment]
@mariusvniekerk

**Comment by quasiben** [comment]
Note, I'll probably only get to writing tests for this later this today or possibly tomorrow ?

**Comment by quasiben** [comment]
Nevermind, test was easy.  Thought I had to spin up yarn to get this going.  It did reveal a bit of clunkiness.  Without setting `autodetect=False` the following will result in nn/rm (most likely) being set to `localhost`

```
YARNCluster(nn="pi", nn_port=31415, rm="e", rm_port=27182..)
```

Perhaps instead I should check if autodetect is false or any values move away from their defaults

**Comment by mariusvniekerk** [comment]
Cool

**Comment by quasiben** [comment]
@mariusvniekerk have you had a chance to test?  Ideally i can merge in the next hour or so

**Pull request merged**
